#!/bin/bash
# installer/macos-pkg/scripts/lib/detect_ram.sh
#
# RAM-tier detection for the Mining Guardian macOS .pkg installer.
#
# Implements decision D-13 (supersedes D-8) from docs/DECISIONS.md:
#
#   16 GB RAM   → llama3.2:3b
#   24 GB+ RAM  → qwen2.5:14b-instruct-q4_K_M
#
# On detect failure (sysctl error, exotic hardware, anything off the happy
# path), the script falls back to llama3.2:3b and writes a LOUD warning to
# stderr + the install log so the operator can override later.
#
# Output contract:
#   - Writes a single shell-sourceable file at $MG_INSTALL_ENV (default
#     /tmp/mg_install_env) containing two assignments:
#         MG_INSTALL_RAM_TIER=<int_gb>
#         MG_INSTALL_LLM_MODEL=<model_string>
#   - Prints a one-line human-readable summary on stdout.
#   - Exit 0 on success (including fallback path).
#   - Exit 1 only if the env file cannot be written (filesystem failure).
#
# This file is sourced by preinstall.sh (Option C / Q1 — hybrid .pkg) and
# read again by postinstall.sh to drive `ollama pull <model>`. It is
# deliberately a separate file from preinstall.sh so it can be unit-tested
# without going through pkg-install machinery.
#
# Vision Anchor 7: local-only. This script makes ZERO network calls.
# Vision Anchor 6: Bitcoin SHA-256 only — has no model knowledge beyond
# the two LLM strings above; no altcoin scaffolding.

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration (no defaults that contradict D-13)
# ---------------------------------------------------------------------------

MG_INSTALL_ENV="${MG_INSTALL_ENV:-/tmp/mg_install_env}"
MG_INSTALL_LOG="${MG_INSTALL_LOG:-/var/log/mining-guardian/install-preinstall.log}"

# D-13 model strings — locked. Changing these requires a new decision.
readonly MODEL_TIER_16GB="llama3.2:3b"
readonly MODEL_TIER_24GB="qwen2.5:14b-instruct-q4_K_M"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

_log() {
    # Best-effort log: never fail the install just because we couldn't
    # tee a line. The log dir is created by preinstall.sh before this
    # helper is sourced; if it doesn't exist, drop the line silently
    # but still echo to stderr so the operator sees it in the GUI log.
    local msg="[detect_ram] $*"
    echo "$msg" >&2
    if [[ -w "$(dirname "$MG_INSTALL_LOG")" ]] 2>/dev/null; then
        echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) $msg" >> "$MG_INSTALL_LOG" 2>/dev/null || true
    fi
}

# ---------------------------------------------------------------------------
# Detect
# ---------------------------------------------------------------------------

detect_ram_gb() {
    # sysctl -n hw.memsize returns bytes on macOS (Darwin). Round DOWN
    # to whole GB using integer math so a 16 GB box (which sysctl
    # actually reports as 17179869184 bytes = exactly 16 * 2^30) lands
    # cleanly on tier 16.
    local bytes
    if ! bytes=$(/usr/sbin/sysctl -n hw.memsize 2>/dev/null); then
        _log "WARN sysctl hw.memsize failed — cannot detect RAM"
        return 1
    fi
    if ! [[ "$bytes" =~ ^[0-9]+$ ]] || [[ "$bytes" -le 0 ]]; then
        _log "WARN sysctl hw.memsize returned non-numeric or zero: '$bytes'"
        return 1
    fi
    # bytes / (1024^3)
    echo $(( bytes / 1073741824 ))
}

select_model_for_tier() {
    local gb="$1"
    if [[ "$gb" -ge 24 ]]; then
        echo "$MODEL_TIER_24GB"
        return 0
    fi
    if [[ "$gb" -ge 16 ]]; then
        echo "$MODEL_TIER_16GB"
        return 0
    fi
    # Below 16 GB is not a supported tier per D-13. We DO NOT
    # silently fall back — preinstall.sh has its own gate for this
    # case and refuses the install. detect_ram.sh just reports the
    # number and lets preinstall make the policy call.
    echo "$MODEL_TIER_16GB"
    return 0
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    local ram_gb model fallback_used="no"

    if ram_gb=$(detect_ram_gb); then
        :
    else
        _log "WARN falling back to RAM tier 16 (sysctl failed)"
        ram_gb=16
        fallback_used="yes"
    fi

    model=$(select_model_for_tier "$ram_gb")

    # Atomic-ish write to MG_INSTALL_ENV. Writing to a temp + mv ensures
    # postinstall.sh never sees a half-written file if preinstall is
    # killed mid-write.
    local tmp="${MG_INSTALL_ENV}.tmp.$$"
    {
        echo "# Generated by detect_ram.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# DO NOT EDIT BY HAND — regenerated on every install run."
        echo "MG_INSTALL_RAM_TIER=${ram_gb}"
        echo "MG_INSTALL_LLM_MODEL=${model}"
        echo "MG_INSTALL_RAM_FALLBACK=${fallback_used}"
    } > "$tmp"

    if ! mv "$tmp" "$MG_INSTALL_ENV"; then
        _log "ERROR could not write $MG_INSTALL_ENV"
        rm -f "$tmp" 2>/dev/null || true
        return 1
    fi

    _log "INFO RAM=${ram_gb}GB → model=${model} (fallback=${fallback_used})"
    echo "Mining Guardian: detected ${ram_gb} GB RAM, will use LLM model '${model}'."
    return 0
}

# Allow the file to be either sourced (for testing) or executed directly
# from preinstall.sh. When sourced, define the functions but don't run
# main(). When executed, run main().
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
